export const MEMORY_BREAKDOWN_FETCH_START = "MEMORY_BREAKDOWN_FETCH_START";
export const MEMORY_BREAKDOWN_FETCH_SUCCESS = "MEMORY_BREAKDOWN_FETCH_SUCCESS";
export const MEMORY_BREAKDOWN_FETCH_FAIL = "MEMORY_BREAKDOWN_FETCH_FAIL";
export const CHANGE_ACTIVE_MEMORY_BREAKDOWN = "CHANGE_ACTIVE_MEMORY_BREAKDOWN";

export const MEMORY_BREAKDOWN_GET_LATEST_START =
  "MEMORY_BREAKDOWN_GET_LATEST_START";
export const MEMORY_BREAKDOWN_GET_LATEST_SUCCESS =
  "MEMORY_BREAKDOWN_GET_LATEST_SUCCESS";
export const MEMORY_BREAKDOWN_GET_LATEST_FAIL =
  "MEMORY_BREAKDOWN_GET_LATEST_FAIL";

export const ASH_MEMORY_BREAKDOWN_GET_LATEST_START =
  "ASH_MEMORY_BREAKDOWN_GET_LATEST_START";
export const ASH_MEMORY_BREAKDOWN_GET_LATEST_SUCCESS =
  "ASH_MEMORY_BREAKDOWN_GET_LATEST_SUCCESS";
export const ASH_MEMORY_BREAKDOWN_GET_LATEST_FAIL =
  "ASH_MEMORY_BREAKDOWN_GET_LATEST_FAIL";

export const ASH_REPORT_FETCH_START = "ASH_REPORT_FETCH_START";
export const ASH_REPORT_FETCH_SUCCESS = "ASH_REPORT_FETCH_SUCCESS";
export const ASH_REPORT_FETCH_FAIL = "ASH_REPORT_FETCH_FAIL";

export const PROCESS_LIST_FETCH_START = "PROCESS_LIST_FETCH_START";
export const PROCESS_LIST_FETCH_SUCCESS = "PROCESS_LIST_FETCH_SUCCESS";
export const PROCESS_LIST_FETCH_FAIL = "PROCESS_LIST_FETCH_FAIL";

export const CLUSTER_STATS_FETCH_START = "CLUSTER_STATS_FETCH_START";
export const CLUSTER_STATS_FETCH_SUCCESS = "CLUSTER_STATS_FETCH_SUCCESS";
export const CLUSTER_STATS_FETCH_FAIL = "CLUSTER_STATS_FETCH_FAIL";

export const CPU_USAGE_FETCH_START = "CPU_USAGE_FETCH_START";
export const CPU_USAGE_FETCH_SUCCESS = "CPU_USAGE_FETCH_SUCCESS";
export const CPU_USAGE_FETCH_FAIL = "CPU_USAGE_FETCH_FAIL";
export const CHANGE_ACTIVE_CPU_USAGE = "CHANGE_ACTIVE_CPU_USAGE";

export const CPU_USAGE_GET_LATEST_START = "CPU_USAGE_GET_LATEST_START";
export const CPU_USAGE_GET_LATEST_SUCCESS = "CPU_USAGE_GET_LATEST_SUCCESS";
export const CPU_USAGE_GET_LATEST_FAIL = "CPU_USAGE_GET_LATEST_FAIL";

export const DISK_USAGE_FETCH_START = "DISK_USAGE_FETCH_START";
export const DISK_USAGE_FETCH_SUCCESS = "DISK_USAGE_FETCH_SUCCESS";
export const DISK_USAGE_FETCH_FAIL = "DISK_USAGE_FETCH_FAIL";
export const CHANGE_ACTIVE_DISK_USAGE = "CHANGE_ACTIVE_DISK_USAGE";

export const DISK_USAGE_GET_LATEST_START = "DISK_USAGE_GET_LATEST_START";
export const DISK_USAGE_GET_LATEST_SUCCESS = "DISK_USAGE_GET_LATEST_SUCCESS";
export const DISK_USAGE_GET_LATEST_FAIL = "DISK_USAGE_GET_LATEST_FAIL";

export const MEMORY_USAGE_FETCH_START = "MEMORY_USAGE_FETCH_START";
export const MEMORY_USAGE_FETCH_SUCCESS = "MEMORY_USAGE_FETCH_SUCCESS";
export const MEMORY_USAGE_FETCH_FAIL = "MEMORY_USAGE_FETCH_FAIL";
export const CHANGE_ACTIVE_MEMORY_USAGE = "CHANGE_ACTIVE_MEMORY_USAGE";

export const CPU_RUNQ_FETCH_START = "CPU_RUNQ_FETCH_START";
export const CPU_RUNQ_FETCH_SUCCESS = "CPU_RUNQ_FETCH_SUCCESS";
export const CPU_RUNQ_FETCH_FAIL = "CPU_RUNQ_FETCH_FAIL";
export const CHANGE_ACTIVE_CPU_RUNQ = "CHANGE_ACTIVE_CPU_RUNQ";

export const MEMORY_USAGE_GET_LATEST_START = "MEMORY_USAGE_GET_LATEST_START";
export const MEMORY_USAGE_GET_LATEST_SUCCESS =
  "MEMORY_USAGE_GET_LATEST_SUCCESS";
export const MEMORY_USAGE_GET_LATEST_FAIL = "MEMORY_USAGE_GET_LATEST_FAIL";

export const SIZES_FETCH_START = "SIZES_FETCH_START";
export const SIZES_FETCH_SUCCESS = "SIZES_FETCH_SUCCES";
export const SIZES_FETCH_FAIL = "SIZES_FETCH_FAIL";
export const CHANGE_SELECTED_DATABASES = "CHANGE_SELECTED_DATABASES";
export const CHANGE_SELECTED_TYPES = "CHANGE_SELECTED_TYPES";

export const SKEW_FETCH_START = "SKEW_FETCH_START";
export const SKEW_FETCH_SUCCESS = "SKEW_FETCH_SUCCESS";
export const SKEW_FETCH_FAIL = "SKEW_FETCH_FAIL";

export const CURRENT_MEMORY_BREAKDOWN_FETCH_START =
  "CURRENT_MEMORY_BREAKDOWN_FETCH_START";
export const CURRENT_MEMORY_BREAKDOWN_FETCH_SUCCESS =
  "CURRENT_MEMORY_BREAKDOWN_FETCH_SUCCESS";
export const CURRENT_MEMORY_BREAKDOWN_FETCH_FAIL =
  "CURRENT_MEMORY_BREAKDOWN_FETCH_FAIL";

export const THREAD_FETCH_START = "THREAD_FETCH_START";
export const THREAD_FETCH_SUCCESS = "THREAD_FETCH_SUCCESS";
export const THREAD_FETCH_FAIL = "THREAD_FETCH_FAIL";
export const THREAD_CHANGE_ACTIVE = "THREAD_CHANGE_ACTIVE";
export const THREAD_GET_LATEST_START = "THREAD_GET_LATEST_START";
export const THREAD_GET_LATEST_SUCCESS = "THREAD_GET_LATEST_SUCCESS";
export const THREAD_GET_LATEST_FAIL = "THREAD_GET_LATEST_FAIL";

export const PROCESS_FETCH_START = "PROCESS_FETCH_START";
export const PROCESS_FETCH_SUCCESS = "PROCESS_FETCH_SUCCESS";
export const PROCESS_FETCH_FAIL = "PROCESS_FETCH_FAIL";
export const PROCESS_CHANGE_ACTIVE = "PROCESS_CHANGE_ACTIVE";
export const PROCESS_GET_LATEST_START = "PROCESS_GET_LATEST_START";
export const PROCESS_GET_LATEST_SUCCESS = "PROCESS_GET_LATEST_SUCCESS";
export const PROCESS_GET_LATEST_FAIL = "PROCESS_GET_LATEST_FAIL";

export const BENCHMARK_FETCH_START = "BENCHMARK_FETCH_START";
export const BENCHMARK_FETCH_SUCCESS = "BENCHMARK_FETCH_SUCCESS";
export const BENCHMARK_FETCH_FAIL = "BENCHMARK_FETCH_FAIL";

export const ADD_HOST_COLORS = "ADD_HOST_COLORS";
export const ADD_NODE_COLORS = "ADD_NODE_COLORS";

export const INIT_HOST_COLORS = "INIT_HOST_COLORS";
export const INIT_NODE_COLORS = "INIT_NODE_COLORS";

export const SET_FROM_TS = "SET_FROM_TS";
export const SET_TO_TS = "SET_TO_TS";
